'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SUNEDU_Consulta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/", ConfigurationName:="SUNEDU_Consulta.ServiceGradoAcademico")>  _
    Public Interface ServiceGradoAcademico
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getGradoAcademico(ByVal request As SUNEDU_Consulta.getGradoAcademico) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> SUNEDU_Consulta.getGradoAcademicoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getGradoAcademicoAsync(ByVal request As SUNEDU_Consulta.getGradoAcademico) As System.Threading.Tasks.Task(Of SUNEDU_Consulta.getGradoAcademicoResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/")>  _
    Partial Public Class UsuarioType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private usuarioField As String
        
        Private claveField As String
        
        Private idEntidadField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
                Me.RaisePropertyChanged("usuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
                Me.RaisePropertyChanged("clave")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property idEntidad() As String
            Get
                Return Me.idEntidadField
            End Get
            Set
                Me.idEntidadField = value
                Me.RaisePropertyChanged("idEntidad")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/")>  _
    Partial Public Class gradoAcademico
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private abreviaturaTituloField As String
        
        Private apellidoMaternoField As String
        
        Private apellidoPaternoField As String
        
        Private especialidadField As String
        
        Private nombresField As String
        
        Private nroDocumentoField As String
        
        Private paisField As String
        
        Private tipoDocumentoField As String
        
        Private tituloProfesionalField As String
        
        Private universidadField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property abreviaturaTitulo() As String
            Get
                Return Me.abreviaturaTituloField
            End Get
            Set
                Me.abreviaturaTituloField = value
                Me.RaisePropertyChanged("abreviaturaTitulo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property apellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
                Me.RaisePropertyChanged("apellidoMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property apellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
                Me.RaisePropertyChanged("apellidoPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property especialidad() As String
            Get
                Return Me.especialidadField
            End Get
            Set
                Me.especialidadField = value
                Me.RaisePropertyChanged("especialidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property nombres() As String
            Get
                Return Me.nombresField
            End Get
            Set
                Me.nombresField = value
                Me.RaisePropertyChanged("nombres")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property nroDocumento() As String
            Get
                Return Me.nroDocumentoField
            End Get
            Set
                Me.nroDocumentoField = value
                Me.RaisePropertyChanged("nroDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
                Me.RaisePropertyChanged("pais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
                Me.RaisePropertyChanged("tipoDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property tituloProfesional() As String
            Get
                Return Me.tituloProfesionalField
            End Get
            Set
                Me.tituloProfesionalField = value
                Me.RaisePropertyChanged("tituloProfesional")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property universidad() As String
            Get
                Return Me.universidadField
            End Get
            Set
                Me.universidadField = value
                Me.RaisePropertyChanged("universidad")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/")>  _
    Partial Public Class RespuestaGradoAcademico
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fecSuneduField As String
        
        Private horSuneduField As String
        
        Private cGenericoField As String
        
        Private dGenericaField As String
        
        Private listaGradoAcademicoField() As gradoAcademico
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property fecSunedu() As String
            Get
                Return Me.fecSuneduField
            End Get
            Set
                Me.fecSuneduField = value
                Me.RaisePropertyChanged("fecSunedu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property horSunedu() As String
            Get
                Return Me.horSuneduField
            End Get
            Set
                Me.horSuneduField = value
                Me.RaisePropertyChanged("horSunedu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property cGenerico() As String
            Get
                Return Me.cGenericoField
            End Get
            Set
                Me.cGenericoField = value
                Me.RaisePropertyChanged("cGenerico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property dGenerica() As String
            Get
                Return Me.dGenericaField
            End Get
            Set
                Me.dGenericaField = value
                Me.RaisePropertyChanged("dGenerica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listaGradoAcademico", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property listaGradoAcademico() As gradoAcademico()
            Get
                Return Me.listaGradoAcademicoField
            End Get
            Set
                Me.listaGradoAcademicoField = value
                Me.RaisePropertyChanged("listaGradoAcademico")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/")>  _
    Partial Public Class OperacionType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fechaField As String
        
        Private horaField As String
        
        Private mac_wsServerField As String
        
        Private ip_wsServerField As String
        
        Private ip_wsUserField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property hora() As String
            Get
                Return Me.horaField
            End Get
            Set
                Me.horaField = value
                Me.RaisePropertyChanged("hora")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property mac_wsServer() As String
            Get
                Return Me.mac_wsServerField
            End Get
            Set
                Me.mac_wsServerField = value
                Me.RaisePropertyChanged("mac_wsServer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property ip_wsServer() As String
            Get
                Return Me.ip_wsServerField
            End Get
            Set
                Me.ip_wsServerField = value
                Me.RaisePropertyChanged("ip_wsServer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property ip_wsUser() As String
            Get
                Return Me.ip_wsUserField
            End Get
            Set
                Me.ip_wsUserField = value
                Me.RaisePropertyChanged("ip_wsUser")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getGradoAcademico", WrapperNamespace:="http://main.wssergraacademico.ongei.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class getGradoAcademico
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuarioType As SUNEDU_Consulta.UsuarioType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public operacionType As SUNEDU_Consulta.OperacionType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public dni As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuarioType As SUNEDU_Consulta.UsuarioType, ByVal operacionType As SUNEDU_Consulta.OperacionType, ByVal dni As String)
            MyBase.New
            Me.usuarioType = usuarioType
            Me.operacionType = operacionType
            Me.dni = dni
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getGradoAcademicoResponse", WrapperNamespace:="http://main.wssergraacademico.ongei.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class getGradoAcademicoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://main.wssergraacademico.ongei.gob.pe/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As SUNEDU_Consulta.RespuestaGradoAcademico
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As SUNEDU_Consulta.RespuestaGradoAcademico)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceGradoAcademicoChannel
        Inherits SUNEDU_Consulta.ServiceGradoAcademico, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceGradoAcademicoClient
        Inherits System.ServiceModel.ClientBase(Of SUNEDU_Consulta.ServiceGradoAcademico)
        Implements SUNEDU_Consulta.ServiceGradoAcademico
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNEDU_Consulta_ServiceGradoAcademico_getGradoAcademico(ByVal request As SUNEDU_Consulta.getGradoAcademico) As SUNEDU_Consulta.getGradoAcademicoResponse Implements SUNEDU_Consulta.ServiceGradoAcademico.getGradoAcademico
            Return MyBase.Channel.getGradoAcademico(request)
        End Function
        
        Public Function getGradoAcademico(ByVal usuarioType As SUNEDU_Consulta.UsuarioType, ByVal operacionType As SUNEDU_Consulta.OperacionType, ByVal dni As String) As SUNEDU_Consulta.RespuestaGradoAcademico
            Dim inValue As SUNEDU_Consulta.getGradoAcademico = New SUNEDU_Consulta.getGradoAcademico()
            inValue.usuarioType = usuarioType
            inValue.operacionType = operacionType
            inValue.dni = dni
            Dim retVal As SUNEDU_Consulta.getGradoAcademicoResponse = CType(Me,SUNEDU_Consulta.ServiceGradoAcademico).getGradoAcademico(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNEDU_Consulta_ServiceGradoAcademico_getGradoAcademicoAsync(ByVal request As SUNEDU_Consulta.getGradoAcademico) As System.Threading.Tasks.Task(Of SUNEDU_Consulta.getGradoAcademicoResponse) Implements SUNEDU_Consulta.ServiceGradoAcademico.getGradoAcademicoAsync
            Return MyBase.Channel.getGradoAcademicoAsync(request)
        End Function
        
        Public Function getGradoAcademicoAsync(ByVal usuarioType As SUNEDU_Consulta.UsuarioType, ByVal operacionType As SUNEDU_Consulta.OperacionType, ByVal dni As String) As System.Threading.Tasks.Task(Of SUNEDU_Consulta.getGradoAcademicoResponse)
            Dim inValue As SUNEDU_Consulta.getGradoAcademico = New SUNEDU_Consulta.getGradoAcademico()
            inValue.usuarioType = usuarioType
            inValue.operacionType = operacionType
            inValue.dni = dni
            Return CType(Me,SUNEDU_Consulta.ServiceGradoAcademico).getGradoAcademicoAsync(inValue)
        End Function
    End Class
End Namespace
