'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace INPE_Consulta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe", ConfigurationName:="INPE_Consulta.verificacionAntecedentesPenalesServicio")>  _
    Public Interface verificacionAntecedentesPenalesServicio
        
        'CODEGEN: Generating message contract since the operation verificarAntecedentesPenales is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe/NewOperation", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function verificarAntecedentesPenales(ByVal request As INPE_Consulta.verificarAntecedentesPenales1) As INPE_Consulta.verificarAntecedentesPenalesResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe/NewOperation", ReplyAction:="*")>  _
        Function verificarAntecedentesPenalesAsync(ByVal request As INPE_Consulta.verificarAntecedentesPenales1) As System.Threading.Tasks.Task(Of INPE_Consulta.verificarAntecedentesPenalesResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")>  _
    Partial Public Class verificarAntecedentesPenales
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xApellidoPaternoField As String
        
        Private xApellidoMaternoField As String
        
        Private xNombre1Field As String
        
        Private xNombre2Field As String
        
        Private xNombre3Field As String
        
        Private xDniField As String
        
        Private xMotivoConsultaField As String
        
        Private xProcesoEntidadConsultanteField As String
        
        Private xRucEntidadConsultanteField As String
        
        Private xDniPersonaConsultanteField As String
        
        Private xAudNombrePCField As String
        
        Private xAudIPField As String
        
        Private xAudNombreUsuarioField As String
        
        Private xAudDireccionMACField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property xApellidoPaterno() As String
            Get
                Return Me.xApellidoPaternoField
            End Get
            Set
                Me.xApellidoPaternoField = value
                Me.RaisePropertyChanged("xApellidoPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property xApellidoMaterno() As String
            Get
                Return Me.xApellidoMaternoField
            End Get
            Set
                Me.xApellidoMaternoField = value
                Me.RaisePropertyChanged("xApellidoMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property xNombre1() As String
            Get
                Return Me.xNombre1Field
            End Get
            Set
                Me.xNombre1Field = value
                Me.RaisePropertyChanged("xNombre1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property xNombre2() As String
            Get
                Return Me.xNombre2Field
            End Get
            Set
                Me.xNombre2Field = value
                Me.RaisePropertyChanged("xNombre2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property xNombre3() As String
            Get
                Return Me.xNombre3Field
            End Get
            Set
                Me.xNombre3Field = value
                Me.RaisePropertyChanged("xNombre3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property xDni() As String
            Get
                Return Me.xDniField
            End Get
            Set
                Me.xDniField = value
                Me.RaisePropertyChanged("xDni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property xMotivoConsulta() As String
            Get
                Return Me.xMotivoConsultaField
            End Get
            Set
                Me.xMotivoConsultaField = value
                Me.RaisePropertyChanged("xMotivoConsulta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property xProcesoEntidadConsultante() As String
            Get
                Return Me.xProcesoEntidadConsultanteField
            End Get
            Set
                Me.xProcesoEntidadConsultanteField = value
                Me.RaisePropertyChanged("xProcesoEntidadConsultante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property xRucEntidadConsultante() As String
            Get
                Return Me.xRucEntidadConsultanteField
            End Get
            Set
                Me.xRucEntidadConsultanteField = value
                Me.RaisePropertyChanged("xRucEntidadConsultante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property xDniPersonaConsultante() As String
            Get
                Return Me.xDniPersonaConsultanteField
            End Get
            Set
                Me.xDniPersonaConsultanteField = value
                Me.RaisePropertyChanged("xDniPersonaConsultante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property xAudNombrePC() As String
            Get
                Return Me.xAudNombrePCField
            End Get
            Set
                Me.xAudNombrePCField = value
                Me.RaisePropertyChanged("xAudNombrePC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property xAudIP() As String
            Get
                Return Me.xAudIPField
            End Get
            Set
                Me.xAudIPField = value
                Me.RaisePropertyChanged("xAudIP")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property xAudNombreUsuario() As String
            Get
                Return Me.xAudNombreUsuarioField
            End Get
            Set
                Me.xAudNombreUsuarioField = value
                Me.RaisePropertyChanged("xAudNombreUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property xAudDireccionMAC() As String
            Get
                Return Me.xAudDireccionMACField
            End Get
            Set
                Me.xAudDireccionMACField = value
                Me.RaisePropertyChanged("xAudDireccionMAC")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")>  _
    Partial Public Class verificarAntecedentesPenalesResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xCodigoRespuestaField As String
        
        Private xMensajeRespuestaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property xCodigoRespuesta() As String
            Get
                Return Me.xCodigoRespuestaField
            End Get
            Set
                Me.xCodigoRespuestaField = value
                Me.RaisePropertyChanged("xCodigoRespuesta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property xMensajeRespuesta() As String
            Get
                Return Me.xMensajeRespuestaField
            End Get
            Set
                Me.xMensajeRespuestaField = value
                Me.RaisePropertyChanged("xMensajeRespuesta")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class verificarAntecedentesPenales1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe", Order:=0)>  _
        Public verificarAntecedentesPenales As INPE_Consulta.verificarAntecedentesPenales
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal verificarAntecedentesPenales As INPE_Consulta.verificarAntecedentesPenales)
            MyBase.New
            Me.verificarAntecedentesPenales = verificarAntecedentesPenales
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class verificarAntecedentesPenalesResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe", Order:=0)>  _
        Public verificarAntecedentesPenalesResponse As INPE_Consulta.verificarAntecedentesPenalesResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal verificarAntecedentesPenalesResponse As INPE_Consulta.verificarAntecedentesPenalesResponse)
            MyBase.New
            Me.verificarAntecedentesPenalesResponse = verificarAntecedentesPenalesResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface verificacionAntecedentesPenalesServicioChannel
        Inherits INPE_Consulta.verificacionAntecedentesPenalesServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class verificacionAntecedentesPenalesServicioClient
        Inherits System.ServiceModel.ClientBase(Of INPE_Consulta.verificacionAntecedentesPenalesServicio)
        Implements INPE_Consulta.verificacionAntecedentesPenalesServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function INPE_Consulta_verificacionAntecedentesPenalesServicio_verificarAntecedentesPenales(ByVal request As INPE_Consulta.verificarAntecedentesPenales1) As INPE_Consulta.verificarAntecedentesPenalesResponse1 Implements INPE_Consulta.verificacionAntecedentesPenalesServicio.verificarAntecedentesPenales
            Return MyBase.Channel.verificarAntecedentesPenales(request)
        End Function
        
        Public Function verificarAntecedentesPenales(ByVal verificarAntecedentesPenales1 As INPE_Consulta.verificarAntecedentesPenales) As INPE_Consulta.verificarAntecedentesPenalesResponse
            Dim inValue As INPE_Consulta.verificarAntecedentesPenales1 = New INPE_Consulta.verificarAntecedentesPenales1()
            inValue.verificarAntecedentesPenales = verificarAntecedentesPenales1
            Dim retVal As INPE_Consulta.verificarAntecedentesPenalesResponse1 = CType(Me,INPE_Consulta.verificacionAntecedentesPenalesServicio).verificarAntecedentesPenales(inValue)
            Return retVal.verificarAntecedentesPenalesResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function INPE_Consulta_verificacionAntecedentesPenalesServicio_verificarAntecedentesPenalesAsync(ByVal request As INPE_Consulta.verificarAntecedentesPenales1) As System.Threading.Tasks.Task(Of INPE_Consulta.verificarAntecedentesPenalesResponse1) Implements INPE_Consulta.verificacionAntecedentesPenalesServicio.verificarAntecedentesPenalesAsync
            Return MyBase.Channel.verificarAntecedentesPenalesAsync(request)
        End Function
        
        Public Function verificarAntecedentesPenalesAsync(ByVal verificarAntecedentesPenales As INPE_Consulta.verificarAntecedentesPenales) As System.Threading.Tasks.Task(Of INPE_Consulta.verificarAntecedentesPenalesResponse1)
            Dim inValue As INPE_Consulta.verificarAntecedentesPenales1 = New INPE_Consulta.verificarAntecedentesPenales1()
            inValue.verificarAntecedentesPenales = verificarAntecedentesPenales
            Return CType(Me,INPE_Consulta.verificacionAntecedentesPenalesServicio).verificarAntecedentesPenalesAsync(inValue)
        End Function
    End Class
End Namespace
