'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace PJ_Consulta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://endpoint.wsantjudiciales.inpe.gob.pe", ConfigurationName:="PJ_Consulta.ServiceAntecedenteJudicial")>  _
    Public Interface ServiceAntecedenteJudicial
        
        'CODEGEN: Generating message contract since element name apepat from namespace http://endpoint.wsantjudiciales.inpe.gob.pe is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAntecedenteJudicial(ByVal request As PJ_Consulta.getAntecedenteJudicialRequest) As PJ_Consulta.getAntecedenteJudicialResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAntecedenteJudicialAsync(ByVal request As PJ_Consulta.getAntecedenteJudicialRequest) As System.Threading.Tasks.Task(Of PJ_Consulta.getAntecedenteJudicialResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAntecedenteJudicialRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAntecedenteJudicial", [Namespace]:="http://endpoint.wsantjudiciales.inpe.gob.pe", Order:=0)>  _
        Public Body As PJ_Consulta.getAntecedenteJudicialRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PJ_Consulta.getAntecedenteJudicialRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://endpoint.wsantjudiciales.inpe.gob.pe")>  _
    Partial Public Class getAntecedenteJudicialRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public apepat As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public apemat As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public nombres As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal apepat As String, ByVal apemat As String, ByVal nombres As String)
            MyBase.New
            Me.apepat = apepat
            Me.apemat = apemat
            Me.nombres = nombres
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAntecedenteJudicialResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAntecedenteJudicialResponse", [Namespace]:="http://endpoint.wsantjudiciales.inpe.gob.pe", Order:=0)>  _
        Public Body As PJ_Consulta.getAntecedenteJudicialResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PJ_Consulta.getAntecedenteJudicialResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://endpoint.wsantjudiciales.inpe.gob.pe")>  _
    Partial Public Class getAntecedenteJudicialResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getAntecedenteJudicialReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getAntecedenteJudicialReturn As String)
            MyBase.New
            Me.getAntecedenteJudicialReturn = getAntecedenteJudicialReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceAntecedenteJudicialChannel
        Inherits PJ_Consulta.ServiceAntecedenteJudicial, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceAntecedenteJudicialClient
        Inherits System.ServiceModel.ClientBase(Of PJ_Consulta.ServiceAntecedenteJudicial)
        Implements PJ_Consulta.ServiceAntecedenteJudicial
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PJ_Consulta_ServiceAntecedenteJudicial_getAntecedenteJudicial(ByVal request As PJ_Consulta.getAntecedenteJudicialRequest) As PJ_Consulta.getAntecedenteJudicialResponse Implements PJ_Consulta.ServiceAntecedenteJudicial.getAntecedenteJudicial
            Return MyBase.Channel.getAntecedenteJudicial(request)
        End Function
        
        Public Function getAntecedenteJudicial(ByVal apepat As String, ByVal apemat As String, ByVal nombres As String) As String
            Dim inValue As PJ_Consulta.getAntecedenteJudicialRequest = New PJ_Consulta.getAntecedenteJudicialRequest()
            inValue.Body = New PJ_Consulta.getAntecedenteJudicialRequestBody()
            inValue.Body.apepat = apepat
            inValue.Body.apemat = apemat
            inValue.Body.nombres = nombres
            Dim retVal As PJ_Consulta.getAntecedenteJudicialResponse = CType(Me,PJ_Consulta.ServiceAntecedenteJudicial).getAntecedenteJudicial(inValue)
            Return retVal.Body.getAntecedenteJudicialReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PJ_Consulta_ServiceAntecedenteJudicial_getAntecedenteJudicialAsync(ByVal request As PJ_Consulta.getAntecedenteJudicialRequest) As System.Threading.Tasks.Task(Of PJ_Consulta.getAntecedenteJudicialResponse) Implements PJ_Consulta.ServiceAntecedenteJudicial.getAntecedenteJudicialAsync
            Return MyBase.Channel.getAntecedenteJudicialAsync(request)
        End Function
        
        Public Function getAntecedenteJudicialAsync(ByVal apepat As String, ByVal apemat As String, ByVal nombres As String) As System.Threading.Tasks.Task(Of PJ_Consulta.getAntecedenteJudicialResponse)
            Dim inValue As PJ_Consulta.getAntecedenteJudicialRequest = New PJ_Consulta.getAntecedenteJudicialRequest()
            inValue.Body = New PJ_Consulta.getAntecedenteJudicialRequestBody()
            inValue.Body.apepat = apepat
            inValue.Body.apemat = apemat
            inValue.Body.nombres = nombres
            Return CType(Me,PJ_Consulta.ServiceAntecedenteJudicial).getAntecedenteJudicialAsync(inValue)
        End Function
    End Class
End Namespace
