'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace AccesoSeguridad
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AccesoSeguridad.ISeguridadService")>  _
    Public Interface ISeguridadService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/ValidarUsuario", ReplyAction:="http://tempuri.org/ISeguridadService/ValidarUsuarioResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidarUsuario(ByVal request As AccesoSeguridad.ValidarUsuarioRequest) As AccesoSeguridad.ValidarUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/ValidarUsuario", ReplyAction:="http://tempuri.org/ISeguridadService/ValidarUsuarioResponse")>  _
        Function ValidarUsuarioAsync(ByVal request As AccesoSeguridad.ValidarUsuarioRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.ValidarUsuarioResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/RegistrarAcceso", ReplyAction:="http://tempuri.org/ISeguridadService/RegistrarAccesoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RegistrarAcceso(ByVal request As AccesoSeguridad.RegistrarAccesoRequest) As AccesoSeguridad.RegistrarAccesoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/RegistrarAcceso", ReplyAction:="http://tempuri.org/ISeguridadService/RegistrarAccesoResponse")>  _
        Function RegistrarAccesoAsync(ByVal request As AccesoSeguridad.RegistrarAccesoRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.RegistrarAccesoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/RegistrarSalida", ReplyAction:="http://tempuri.org/ISeguridadService/RegistrarSalidaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RegistrarSalida(ByVal request As AccesoSeguridad.RegistrarSalidaRequest) As AccesoSeguridad.RegistrarSalidaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/RegistrarSalida", ReplyAction:="http://tempuri.org/ISeguridadService/RegistrarSalidaResponse")>  _
        Function RegistrarSalidaAsync(ByVal request As AccesoSeguridad.RegistrarSalidaRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.RegistrarSalidaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/ListarOpUsuario", ReplyAction:="http://tempuri.org/ISeguridadService/ListarOpUsuarioResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarOpUsuario(ByVal request As AccesoSeguridad.ListarOpUsuarioRequest) As AccesoSeguridad.ListarOpUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISeguridadService/ListarOpUsuario", ReplyAction:="http://tempuri.org/ISeguridadService/ListarOpUsuarioResponse")>  _
        Function ListarOpUsuarioAsync(ByVal request As AccesoSeguridad.ListarOpUsuarioRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.ListarOpUsuarioResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAplicacionField As String
        
        Private tipoUsuarioField As String
        
        Private nombreUsuarioField As String
        
        Private passwordField As String
        
        Private tipoValidacionField As TipoValidacion
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.codigoAplicacionField
            End Get
            Set
                Me.codigoAplicacionField = value
                Me.RaisePropertyChanged("CodigoAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property TipoUsuario() As String
            Get
                Return Me.tipoUsuarioField
            End Get
            Set
                Me.tipoUsuarioField = value
                Me.RaisePropertyChanged("TipoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NombreUsuario() As String
            Get
                Return Me.nombreUsuarioField
            End Get
            Set
                Me.nombreUsuarioField = value
                Me.RaisePropertyChanged("NombreUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("Password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property TipoValidacion() As TipoValidacion
            Get
                Return Me.tipoValidacionField
            End Get
            Set
                Me.tipoValidacionField = value
                Me.RaisePropertyChanged("TipoValidacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoValidacion
        
        '''<remarks/>
        Windows
        
        '''<remarks/>
        Forms
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListarOpUsuarioResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private correctoField As Boolean
        
        Private mensajeErrorField As String
        
        Private usuarioField As UsuarioBE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Correcto() As Boolean
            Get
                Return Me.correctoField
            End Get
            Set
                Me.correctoField = value
                Me.RaisePropertyChanged("Correcto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Usuario() As UsuarioBE
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
                Me.RaisePropertyChanged("Usuario")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UsuarioBE
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoUsuarioField As String
        
        Private nombreUsuarioField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private usuarioLogonField As String
        
        Private usuarioPasswordField As String
        
        Private correoElectronicoField As String
        
        Private tipoUsuarioField As String
        
        Private estadoUsuarioField As String
        
        Private codigoGerenciaField As String
        
        Private codigoPerfilField As String
        
        Private descripcionPerfilField As String
        
        Private listaUsuarioPerfilField() As UsuarioPerfilBE
        
        Private listaUsuarioPerfilOpcionField() As UsuarioPerfilOpcionBE
        
        Private estacionUsuarioField As String
        
        Private usuarioNTField As String
        
        Private dataSetUsuarioPerfilOpcionField As System.Data.DataSet
        
        Private codigoAplicacionField As String
        
        Private flagResetClaveField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoUsuario() As String
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
                Me.RaisePropertyChanged("CodigoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NombreUsuario() As String
            Get
                Return Me.nombreUsuarioField
            End Get
            Set
                Me.nombreUsuarioField = value
                Me.RaisePropertyChanged("NombreUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
                Me.RaisePropertyChanged("ApellidoPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
                Me.RaisePropertyChanged("ApellidoMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UsuarioLogon() As String
            Get
                Return Me.usuarioLogonField
            End Get
            Set
                Me.usuarioLogonField = value
                Me.RaisePropertyChanged("UsuarioLogon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioPassword() As String
            Get
                Return Me.usuarioPasswordField
            End Get
            Set
                Me.usuarioPasswordField = value
                Me.RaisePropertyChanged("UsuarioPassword")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property CorreoElectronico() As String
            Get
                Return Me.correoElectronicoField
            End Get
            Set
                Me.correoElectronicoField = value
                Me.RaisePropertyChanged("CorreoElectronico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property TipoUsuario() As String
            Get
                Return Me.tipoUsuarioField
            End Get
            Set
                Me.tipoUsuarioField = value
                Me.RaisePropertyChanged("TipoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property EstadoUsuario() As String
            Get
                Return Me.estadoUsuarioField
            End Get
            Set
                Me.estadoUsuarioField = value
                Me.RaisePropertyChanged("EstadoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property CodigoGerencia() As String
            Get
                Return Me.codigoGerenciaField
            End Get
            Set
                Me.codigoGerenciaField = value
                Me.RaisePropertyChanged("CodigoGerencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property CodigoPerfil() As String
            Get
                Return Me.codigoPerfilField
            End Get
            Set
                Me.codigoPerfilField = value
                Me.RaisePropertyChanged("CodigoPerfil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property DescripcionPerfil() As String
            Get
                Return Me.descripcionPerfilField
            End Get
            Set
                Me.descripcionPerfilField = value
                Me.RaisePropertyChanged("DescripcionPerfil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=12)>  _
        Public Property ListaUsuarioPerfil() As UsuarioPerfilBE()
            Get
                Return Me.listaUsuarioPerfilField
            End Get
            Set
                Me.listaUsuarioPerfilField = value
                Me.RaisePropertyChanged("ListaUsuarioPerfil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=13)>  _
        Public Property ListaUsuarioPerfilOpcion() As UsuarioPerfilOpcionBE()
            Get
                Return Me.listaUsuarioPerfilOpcionField
            End Get
            Set
                Me.listaUsuarioPerfilOpcionField = value
                Me.RaisePropertyChanged("ListaUsuarioPerfilOpcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property EstacionUsuario() As String
            Get
                Return Me.estacionUsuarioField
            End Get
            Set
                Me.estacionUsuarioField = value
                Me.RaisePropertyChanged("EstacionUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property UsuarioNT() As String
            Get
                Return Me.usuarioNTField
            End Get
            Set
                Me.usuarioNTField = value
                Me.RaisePropertyChanged("UsuarioNT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property DataSetUsuarioPerfilOpcion() As System.Data.DataSet
            Get
                Return Me.dataSetUsuarioPerfilOpcionField
            End Get
            Set
                Me.dataSetUsuarioPerfilOpcionField = value
                Me.RaisePropertyChanged("DataSetUsuarioPerfilOpcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.codigoAplicacionField
            End Get
            Set
                Me.codigoAplicacionField = value
                Me.RaisePropertyChanged("CodigoAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property FlagResetClave() As Boolean
            Get
                Return Me.flagResetClaveField
            End Get
            Set
                Me.flagResetClaveField = value
                Me.RaisePropertyChanged("FlagResetClave")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UsuarioPerfilBE
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoUsuarioField As String
        
        Private codigoAplicacionField As String
        
        Private codigoPerfilField As String
        
        Private nombreUsuarioField As String
        
        Private descripcionPerfilField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoUsuario() As String
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
                Me.RaisePropertyChanged("CodigoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.codigoAplicacionField
            End Get
            Set
                Me.codigoAplicacionField = value
                Me.RaisePropertyChanged("CodigoAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CodigoPerfil() As String
            Get
                Return Me.codigoPerfilField
            End Get
            Set
                Me.codigoPerfilField = value
                Me.RaisePropertyChanged("CodigoPerfil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NombreUsuario() As String
            Get
                Return Me.nombreUsuarioField
            End Get
            Set
                Me.nombreUsuarioField = value
                Me.RaisePropertyChanged("NombreUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property DescripcionPerfil() As String
            Get
                Return Me.descripcionPerfilField
            End Get
            Set
                Me.descripcionPerfilField = value
                Me.RaisePropertyChanged("DescripcionPerfil")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UsuarioPerfilOpcionBE
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAplicacionField As String
        
        Private codigoUsuarioField As String
        
        Private codigoPerfilField As String
        
        Private codigoOpcionField As String
        
        Private codigoSecuencialField As String
        
        Private denominacionField As String
        
        Private nombrePaginaField As String
        
        Private tipoOpcionField As String
        
        Private tipoPublicoField As String
        
        Private tipoAccesoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.codigoAplicacionField
            End Get
            Set
                Me.codigoAplicacionField = value
                Me.RaisePropertyChanged("CodigoAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoUsuario() As String
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
                Me.RaisePropertyChanged("CodigoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CodigoPerfil() As String
            Get
                Return Me.codigoPerfilField
            End Get
            Set
                Me.codigoPerfilField = value
                Me.RaisePropertyChanged("CodigoPerfil")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property CodigoOpcion() As String
            Get
                Return Me.codigoOpcionField
            End Get
            Set
                Me.codigoOpcionField = value
                Me.RaisePropertyChanged("CodigoOpcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property CodigoSecuencial() As String
            Get
                Return Me.codigoSecuencialField
            End Get
            Set
                Me.codigoSecuencialField = value
                Me.RaisePropertyChanged("CodigoSecuencial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Denominacion() As String
            Get
                Return Me.denominacionField
            End Get
            Set
                Me.denominacionField = value
                Me.RaisePropertyChanged("Denominacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property NombrePagina() As String
            Get
                Return Me.nombrePaginaField
            End Get
            Set
                Me.nombrePaginaField = value
                Me.RaisePropertyChanged("NombrePagina")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property TipoOpcion() As String
            Get
                Return Me.tipoOpcionField
            End Get
            Set
                Me.tipoOpcionField = value
                Me.RaisePropertyChanged("TipoOpcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TipoPublico() As String
            Get
                Return Me.tipoPublicoField
            End Get
            Set
                Me.tipoPublicoField = value
                Me.RaisePropertyChanged("TipoPublico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property TipoAcceso() As String
            Get
                Return Me.tipoAccesoField
            End Get
            Set
                Me.tipoAccesoField = value
                Me.RaisePropertyChanged("TipoAcceso")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListarOpUsuarioRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoTransfSesionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoTransfSesion() As String
            Get
                Return Me.codigoTransfSesionField
            End Get
            Set
                Me.codigoTransfSesionField = value
                Me.RaisePropertyChanged("CodigoTransfSesion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RegistrarSalidaResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private correctoField As Boolean
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Correcto() As Boolean
            Get
                Return Me.correctoField
            End Get
            Set
                Me.correctoField = value
                Me.RaisePropertyChanged("Correcto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RegistrarSalidaRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nCOUTILField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NCOUTIL() As String
            Get
                Return Me.nCOUTILField
            End Get
            Set
                Me.nCOUTILField = value
                Me.RaisePropertyChanged("NCOUTIL")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RegistrarAccesoResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private correctoField As Boolean
        
        Private mensajeErrorField As String
        
        Private nCOUTILField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Correcto() As Boolean
            Get
                Return Me.correctoField
            End Get
            Set
                Me.correctoField = value
                Me.RaisePropertyChanged("Correcto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NCOUTIL() As Integer
            Get
                Return Me.nCOUTILField
            End Get
            Set
                Me.nCOUTILField = value
                Me.RaisePropertyChanged("NCOUTIL")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RegistrarAccesoRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAplicacionField As String
        
        Private codigoOpcionField As String
        
        Private codigoUsuarioField As String
        
        Private direccionIPField As String
        
        Private nombrePCField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.codigoAplicacionField
            End Get
            Set
                Me.codigoAplicacionField = value
                Me.RaisePropertyChanged("CodigoAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoOpcion() As String
            Get
                Return Me.codigoOpcionField
            End Get
            Set
                Me.codigoOpcionField = value
                Me.RaisePropertyChanged("CodigoOpcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CodigoUsuario() As String
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
                Me.RaisePropertyChanged("CodigoUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property DireccionIP() As String
            Get
                Return Me.direccionIPField
            End Get
            Set
                Me.direccionIPField = value
                Me.RaisePropertyChanged("DireccionIP")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property NombrePC() As String
            Get
                Return Me.nombrePCField
            End Get
            Set
                Me.nombrePCField = value
                Me.RaisePropertyChanged("NombrePC")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private correctoField As Boolean
        
        Private mensajeErrorField As String
        
        Private usuarioField As UsuarioBE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Correcto() As Boolean
            Get
                Return Me.correctoField
            End Get
            Set
                Me.correctoField = value
                Me.RaisePropertyChanged("Correcto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Usuario() As UsuarioBE
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
                Me.RaisePropertyChanged("Usuario")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISeguridadServiceChannel
        Inherits AccesoSeguridad.ISeguridadService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SeguridadServiceClient
        Inherits System.ServiceModel.ClientBase(Of AccesoSeguridad.ISeguridadService)
        Implements AccesoSeguridad.ISeguridadService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidarUsuario(ByVal request As AccesoSeguridad.ValidarUsuarioRequest) As AccesoSeguridad.ValidarUsuarioResponse Implements AccesoSeguridad.ISeguridadService.ValidarUsuario
            Return MyBase.Channel.ValidarUsuario(request)
        End Function
        
        Public Function ValidarUsuarioAsync(ByVal request As AccesoSeguridad.ValidarUsuarioRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.ValidarUsuarioResponse) Implements AccesoSeguridad.ISeguridadService.ValidarUsuarioAsync
            Return MyBase.Channel.ValidarUsuarioAsync(request)
        End Function
        
        Public Function RegistrarAcceso(ByVal request As AccesoSeguridad.RegistrarAccesoRequest) As AccesoSeguridad.RegistrarAccesoResponse Implements AccesoSeguridad.ISeguridadService.RegistrarAcceso
            Return MyBase.Channel.RegistrarAcceso(request)
        End Function
        
        Public Function RegistrarAccesoAsync(ByVal request As AccesoSeguridad.RegistrarAccesoRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.RegistrarAccesoResponse) Implements AccesoSeguridad.ISeguridadService.RegistrarAccesoAsync
            Return MyBase.Channel.RegistrarAccesoAsync(request)
        End Function
        
        Public Function RegistrarSalida(ByVal request As AccesoSeguridad.RegistrarSalidaRequest) As AccesoSeguridad.RegistrarSalidaResponse Implements AccesoSeguridad.ISeguridadService.RegistrarSalida
            Return MyBase.Channel.RegistrarSalida(request)
        End Function
        
        Public Function RegistrarSalidaAsync(ByVal request As AccesoSeguridad.RegistrarSalidaRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.RegistrarSalidaResponse) Implements AccesoSeguridad.ISeguridadService.RegistrarSalidaAsync
            Return MyBase.Channel.RegistrarSalidaAsync(request)
        End Function
        
        Public Function ListarOpUsuario(ByVal request As AccesoSeguridad.ListarOpUsuarioRequest) As AccesoSeguridad.ListarOpUsuarioResponse Implements AccesoSeguridad.ISeguridadService.ListarOpUsuario
            Return MyBase.Channel.ListarOpUsuario(request)
        End Function
        
        Public Function ListarOpUsuarioAsync(ByVal request As AccesoSeguridad.ListarOpUsuarioRequest) As System.Threading.Tasks.Task(Of AccesoSeguridad.ListarOpUsuarioResponse) Implements AccesoSeguridad.ISeguridadService.ListarOpUsuarioAsync
            Return MyBase.Channel.ListarOpUsuarioAsync(request)
        End Function
    End Class
End Namespace
