'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SUNARP_Consulta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/", ConfigurationName:="SUNARP_Consulta.PIDEWSService")>  _
    Public Interface PIDEWSService
        
        'CODEGEN: Parameter 'respuestaTitularidad' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarTitularidad(ByVal request As SUNARP_Consulta.buscarTitularidadRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="respuestaTitularidad")> SUNARP_Consulta.buscarTitularidadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/buscarTitularidadResponse")>  _
        Function buscarTitularidadAsync(ByVal request As SUNARP_Consulta.buscarTitularidadRequest) As System.Threading.Tasks.Task(Of SUNARP_Consulta.buscarTitularidadResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/generarVigenciaRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/generarVigenciaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function generarVigencia(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal asiento As String, ByVal apPaterno As String, ByVal apMaterno As String, ByVal nombre As String, ByVal cargo As String, ByVal email As String) As <System.ServiceModel.MessageParameterAttribute(Name:="datosVigencia")> SUNARP_Consulta.respuestaSolicitudBean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/generarVigenciaRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/generarVigenciaResponse")>  _
        Function generarVigenciaAsync(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal asiento As String, ByVal apPaterno As String, ByVal apMaterno As String, ByVal nombre As String, ByVal cargo As String, ByVal email As String) As <System.ServiceModel.MessageParameterAttribute(Name:="datosVigencia")> System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaSolicitudBean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function listarAsientos(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal registro As String) As <System.ServiceModel.MessageParameterAttribute(Name:="asientos")> SUNARP_Consulta.respuestaPartidaBean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/listarAsientosResponse")>  _
        Function listarAsientosAsync(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal registro As String) As <System.ServiceModel.MessageParameterAttribute(Name:="asientos")> System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaPartidaBean)
        
        'CODEGEN: Parameter 'img' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function verAsiento(ByVal request As SUNARP_Consulta.verAsientoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="img")> SUNARP_Consulta.verAsientoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verAsientoResponse")>  _
        Function verAsientoAsync(ByVal request As SUNARP_Consulta.verAsientoRequest) As System.Threading.Tasks.Task(Of SUNARP_Consulta.verAsientoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function verDetalleRPV(ByVal zona As String, ByVal oficina As String, ByVal placa As String) As <System.ServiceModel.MessageParameterAttribute(Name:="vehiculo")> SUNARP_Consulta.respuestaVehiculoBean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVRequest", ReplyAction:="http://controller.pide.sunarp.gob.pe/PIDEWSService/verDetalleRPVResponse")>  _
        Function verDetalleRPVAsync(ByVal zona As String, ByVal oficina As String, ByVal placa As String) As <System.ServiceModel.MessageParameterAttribute(Name:="vehiculo")> System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaVehiculoBean)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class respuestaTitularidadBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private registroField As String
        
        Private apPaternoField As String
        
        Private apMaternoField As String
        
        Private nombreField As String
        
        Private razonSocialField As String
        
        Private tipoDocumentoField As String
        
        Private numeroDocumentoField As String
        
        Private numeroPartidaField As String
        
        Private numeroPlacaField As String
        
        Private estadoField As String
        
        Private zonaField As String
        
        Private oficinaField As String
        
        Private mensajeField As String
        
        Private direccionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property registro() As String
            Get
                Return Me.registroField
            End Get
            Set
                Me.registroField = value
                Me.RaisePropertyChanged("registro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property apPaterno() As String
            Get
                Return Me.apPaternoField
            End Get
            Set
                Me.apPaternoField = value
                Me.RaisePropertyChanged("apPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property apMaterno() As String
            Get
                Return Me.apMaternoField
            End Get
            Set
                Me.apMaternoField = value
                Me.RaisePropertyChanged("apMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
                Me.RaisePropertyChanged("razonSocial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
                Me.RaisePropertyChanged("tipoDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
                Me.RaisePropertyChanged("numeroDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property numeroPartida() As String
            Get
                Return Me.numeroPartidaField
            End Get
            Set
                Me.numeroPartidaField = value
                Me.RaisePropertyChanged("numeroPartida")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property numeroPlaca() As String
            Get
                Return Me.numeroPlacaField
            End Get
            Set
                Me.numeroPlacaField = value
                Me.RaisePropertyChanged("numeroPlaca")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property zona() As String
            Get
                Return Me.zonaField
            End Get
            Set
                Me.zonaField = value
                Me.RaisePropertyChanged("zona")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property oficina() As String
            Get
                Return Me.oficinaField
            End Get
            Set
                Me.oficinaField = value
                Me.RaisePropertyChanged("oficina")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class respuestaVehiculoBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private placaField As String
        
        Private serieField As String
        
        Private vinField As String
        
        Private nro_motorField As String
        
        Private colorField As String
        
        Private marcaField As String
        
        Private modeloField As String
        
        Private estadoField As String
        
        Private sedeField As String
        
        Private propietariosField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
                Me.RaisePropertyChanged("placa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("serie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property vin() As String
            Get
                Return Me.vinField
            End Get
            Set
                Me.vinField = value
                Me.RaisePropertyChanged("vin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property nro_motor() As String
            Get
                Return Me.nro_motorField
            End Get
            Set
                Me.nro_motorField = value
                Me.RaisePropertyChanged("nro_motor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
                Me.RaisePropertyChanged("color")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property marca() As String
            Get
                Return Me.marcaField
            End Get
            Set
                Me.marcaField = value
                Me.RaisePropertyChanged("marca")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property modelo() As String
            Get
                Return Me.modeloField
            End Get
            Set
                Me.modeloField = value
                Me.RaisePropertyChanged("modelo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property sede() As String
            Get
                Return Me.sedeField
            End Get
            Set
                Me.sedeField = value
                Me.RaisePropertyChanged("sede")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9),  _
         System.Xml.Serialization.XmlArrayItemAttribute("nombre", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property propietarios() As String()
            Get
                Return Me.propietariosField
            End Get
            Set
                Me.propietariosField = value
                Me.RaisePropertyChanged("propietarios")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class tomoFolioBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idImgFolioField As Decimal
        
        Private idImgFolioFieldSpecified As Boolean
        
        Private nroPagRefField As String
        
        Private paginaField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property idImgFolio() As Decimal
            Get
                Return Me.idImgFolioField
            End Get
            Set
                Me.idImgFolioField = value
                Me.RaisePropertyChanged("idImgFolio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImgFolioSpecified() As Boolean
            Get
                Return Me.idImgFolioFieldSpecified
            End Get
            Set
                Me.idImgFolioFieldSpecified = value
                Me.RaisePropertyChanged("idImgFolioSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nroPagRef() As String
            Get
                Return Me.nroPagRefField
            End Get
            Set
                Me.nroPagRefField = value
                Me.RaisePropertyChanged("nroPagRef")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property pagina() As String
            Get
                Return Me.paginaField
            End Get
            Set
                Me.paginaField = value
                Me.RaisePropertyChanged("pagina")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("tipo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class fichaBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idImgFichaField As Decimal
        
        Private idImgFichaFieldSpecified As Boolean
        
        Private numPagField As Decimal
        
        Private numPagFieldSpecified As Boolean
        
        Private tipoField As String
        
        Private listPagField() As numeroPaginasBean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property idImgFicha() As Decimal
            Get
                Return Me.idImgFichaField
            End Get
            Set
                Me.idImgFichaField = value
                Me.RaisePropertyChanged("idImgFicha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImgFichaSpecified() As Boolean
            Get
                Return Me.idImgFichaFieldSpecified
            End Get
            Set
                Me.idImgFichaFieldSpecified = value
                Me.RaisePropertyChanged("idImgFichaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property numPag() As Decimal
            Get
                Return Me.numPagField
            End Get
            Set
                Me.numPagField = value
                Me.RaisePropertyChanged("numPag")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numPagSpecified() As Boolean
            Get
                Return Me.numPagFieldSpecified
            End Get
            Set
                Me.numPagFieldSpecified = value
                Me.RaisePropertyChanged("numPagSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("tipo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listPag", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property listPag() As numeroPaginasBean()
            Get
                Return Me.listPagField
            End Get
            Set
                Me.listPagField = value
                Me.RaisePropertyChanged("listPag")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class numeroPaginasBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nroPagRefField As String
        
        Private paginaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nroPagRef() As String
            Get
                Return Me.nroPagRefField
            End Get
            Set
                Me.nroPagRefField = value
                Me.RaisePropertyChanged("nroPagRef")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property pagina() As String
            Get
                Return Me.paginaField
            End Get
            Set
                Me.paginaField = value
                Me.RaisePropertyChanged("pagina")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class asientosBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idImgAsientoField As Decimal
        
        Private idImgAsientoFieldSpecified As Boolean
        
        Private numPagField As Decimal
        
        Private numPagFieldSpecified As Boolean
        
        Private tipoField As String
        
        Private listPagField() As numeroPaginasBean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property idImgAsiento() As Decimal
            Get
                Return Me.idImgAsientoField
            End Get
            Set
                Me.idImgAsientoField = value
                Me.RaisePropertyChanged("idImgAsiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImgAsientoSpecified() As Boolean
            Get
                Return Me.idImgAsientoFieldSpecified
            End Get
            Set
                Me.idImgAsientoFieldSpecified = value
                Me.RaisePropertyChanged("idImgAsientoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property numPag() As Decimal
            Get
                Return Me.numPagField
            End Get
            Set
                Me.numPagField = value
                Me.RaisePropertyChanged("numPag")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numPagSpecified() As Boolean
            Get
                Return Me.numPagFieldSpecified
            End Get
            Set
                Me.numPagFieldSpecified = value
                Me.RaisePropertyChanged("numPagSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("tipo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listPag", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property listPag() As numeroPaginasBean()
            Get
                Return Me.listPagField
            End Get
            Set
                Me.listPagField = value
                Me.RaisePropertyChanged("listPag")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class respuestaPartidaBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private transaccionField As Long
        
        Private nroTotalPagField As String
        
        Private listAsientosField() As asientosBean
        
        Private listFichasField() As fichaBean
        
        Private listFoliosField() As tomoFolioBean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property transaccion() As Long
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
                Me.RaisePropertyChanged("transaccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nroTotalPag() As String
            Get
                Return Me.nroTotalPagField
            End Get
            Set
                Me.nroTotalPagField = value
                Me.RaisePropertyChanged("nroTotalPag")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listAsientos", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property listAsientos() As asientosBean()
            Get
                Return Me.listAsientosField
            End Get
            Set
                Me.listAsientosField = value
                Me.RaisePropertyChanged("listAsientos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listFichas", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property listFichas() As fichaBean()
            Get
                Return Me.listFichasField
            End Get
            Set
                Me.listFichasField = value
                Me.RaisePropertyChanged("listFichas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listFolios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property listFolios() As tomoFolioBean()
            Get
                Return Me.listFoliosField
            End Get
            Set
                Me.listFoliosField = value
                Me.RaisePropertyChanged("listFolios")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://controller.pide.sunarp.gob.pe/")>  _
    Partial Public Class respuestaSolicitudBean
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estadoField As String
        
        Private solicitudField As Long
        
        Private fechaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property solicitud() As Long
            Get
                Return Me.solicitudField
            End Get
            Set
                Me.solicitudField = value
                Me.RaisePropertyChanged("solicitud")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="buscarTitularidad", WrapperNamespace:="http://controller.pide.sunarp.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class buscarTitularidadRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public tipoParticipante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public apellidoPaterno As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public apellidoMaterno As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nombres As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public razonSocial As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tipoParticipante As String, ByVal apellidoPaterno As String, ByVal apellidoMaterno As String, ByVal nombres As String, ByVal razonSocial As String)
            MyBase.New
            Me.tipoParticipante = tipoParticipante
            Me.apellidoPaterno = apellidoPaterno
            Me.apellidoMaterno = apellidoMaterno
            Me.nombres = nombres
            Me.razonSocial = razonSocial
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="buscarTitularidadResponse", WrapperNamespace:="http://controller.pide.sunarp.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class buscarTitularidadResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(),  _
         System.Xml.Serialization.XmlArrayItemAttribute("respuestaTitularidad", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public respuestaTitularidad() As SUNARP_Consulta.respuestaTitularidadBean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal respuestaTitularidad() As SUNARP_Consulta.respuestaTitularidadBean)
            MyBase.New
            Me.respuestaTitularidad = respuestaTitularidad
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verAsiento", WrapperNamespace:="http://controller.pide.sunarp.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class verAsientoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public transaccion As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public idImg As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public tipo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nroTotalPag As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public nroPagRef As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public pagina As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal transaccion As Long, ByVal idImg As Long, ByVal tipo As String, ByVal nroTotalPag As String, ByVal nroPagRef As String, ByVal pagina As String)
            MyBase.New
            Me.transaccion = transaccion
            Me.idImg = idImg
            Me.tipo = tipo
            Me.nroTotalPag = nroTotalPag
            Me.nroPagRef = nroPagRef
            Me.pagina = pagina
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verAsientoResponse", WrapperNamespace:="http://controller.pide.sunarp.gob.pe/", IsWrapped:=true)>  _
    Partial Public Class verAsientoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public img() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal img() As Byte)
            MyBase.New
            Me.img = img
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PIDEWSServiceChannel
        Inherits SUNARP_Consulta.PIDEWSService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PIDEWSServiceClient
        Inherits System.ServiceModel.ClientBase(Of SUNARP_Consulta.PIDEWSService)
        Implements SUNARP_Consulta.PIDEWSService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNARP_Consulta_PIDEWSService_buscarTitularidad(ByVal request As SUNARP_Consulta.buscarTitularidadRequest) As SUNARP_Consulta.buscarTitularidadResponse Implements SUNARP_Consulta.PIDEWSService.buscarTitularidad
            Return MyBase.Channel.buscarTitularidad(request)
        End Function
        
        Public Function buscarTitularidad(ByVal tipoParticipante As String, ByVal apellidoPaterno As String, ByVal apellidoMaterno As String, ByVal nombres As String, ByVal razonSocial As String) As SUNARP_Consulta.respuestaTitularidadBean()
            Dim inValue As SUNARP_Consulta.buscarTitularidadRequest = New SUNARP_Consulta.buscarTitularidadRequest()
            inValue.tipoParticipante = tipoParticipante
            inValue.apellidoPaterno = apellidoPaterno
            inValue.apellidoMaterno = apellidoMaterno
            inValue.nombres = nombres
            inValue.razonSocial = razonSocial
            Dim retVal As SUNARP_Consulta.buscarTitularidadResponse = CType(Me,SUNARP_Consulta.PIDEWSService).buscarTitularidad(inValue)
            Return retVal.respuestaTitularidad
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNARP_Consulta_PIDEWSService_buscarTitularidadAsync(ByVal request As SUNARP_Consulta.buscarTitularidadRequest) As System.Threading.Tasks.Task(Of SUNARP_Consulta.buscarTitularidadResponse) Implements SUNARP_Consulta.PIDEWSService.buscarTitularidadAsync
            Return MyBase.Channel.buscarTitularidadAsync(request)
        End Function
        
        Public Function buscarTitularidadAsync(ByVal tipoParticipante As String, ByVal apellidoPaterno As String, ByVal apellidoMaterno As String, ByVal nombres As String, ByVal razonSocial As String) As System.Threading.Tasks.Task(Of SUNARP_Consulta.buscarTitularidadResponse)
            Dim inValue As SUNARP_Consulta.buscarTitularidadRequest = New SUNARP_Consulta.buscarTitularidadRequest()
            inValue.tipoParticipante = tipoParticipante
            inValue.apellidoPaterno = apellidoPaterno
            inValue.apellidoMaterno = apellidoMaterno
            inValue.nombres = nombres
            inValue.razonSocial = razonSocial
            Return CType(Me,SUNARP_Consulta.PIDEWSService).buscarTitularidadAsync(inValue)
        End Function
        
        Public Function generarVigencia(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal asiento As String, ByVal apPaterno As String, ByVal apMaterno As String, ByVal nombre As String, ByVal cargo As String, ByVal email As String) As SUNARP_Consulta.respuestaSolicitudBean Implements SUNARP_Consulta.PIDEWSService.generarVigencia
            Return MyBase.Channel.generarVigencia(zona, oficina, partida, asiento, apPaterno, apMaterno, nombre, cargo, email)
        End Function
        
        Public Function generarVigenciaAsync(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal asiento As String, ByVal apPaterno As String, ByVal apMaterno As String, ByVal nombre As String, ByVal cargo As String, ByVal email As String) As System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaSolicitudBean) Implements SUNARP_Consulta.PIDEWSService.generarVigenciaAsync
            Return MyBase.Channel.generarVigenciaAsync(zona, oficina, partida, asiento, apPaterno, apMaterno, nombre, cargo, email)
        End Function
        
        Public Function listarAsientos(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal registro As String) As SUNARP_Consulta.respuestaPartidaBean Implements SUNARP_Consulta.PIDEWSService.listarAsientos
            Return MyBase.Channel.listarAsientos(zona, oficina, partida, registro)
        End Function
        
        Public Function listarAsientosAsync(ByVal zona As String, ByVal oficina As String, ByVal partida As String, ByVal registro As String) As System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaPartidaBean) Implements SUNARP_Consulta.PIDEWSService.listarAsientosAsync
            Return MyBase.Channel.listarAsientosAsync(zona, oficina, partida, registro)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNARP_Consulta_PIDEWSService_verAsiento(ByVal request As SUNARP_Consulta.verAsientoRequest) As SUNARP_Consulta.verAsientoResponse Implements SUNARP_Consulta.PIDEWSService.verAsiento
            Return MyBase.Channel.verAsiento(request)
        End Function
        
        Public Function verAsiento(ByVal transaccion As Long, ByVal idImg As Long, ByVal tipo As String, ByVal nroTotalPag As String, ByVal nroPagRef As String, ByVal pagina As String) As Byte()
            Dim inValue As SUNARP_Consulta.verAsientoRequest = New SUNARP_Consulta.verAsientoRequest()
            inValue.transaccion = transaccion
            inValue.idImg = idImg
            inValue.tipo = tipo
            inValue.nroTotalPag = nroTotalPag
            inValue.nroPagRef = nroPagRef
            inValue.pagina = pagina
            Dim retVal As SUNARP_Consulta.verAsientoResponse = CType(Me,SUNARP_Consulta.PIDEWSService).verAsiento(inValue)
            Return retVal.img
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SUNARP_Consulta_PIDEWSService_verAsientoAsync(ByVal request As SUNARP_Consulta.verAsientoRequest) As System.Threading.Tasks.Task(Of SUNARP_Consulta.verAsientoResponse) Implements SUNARP_Consulta.PIDEWSService.verAsientoAsync
            Return MyBase.Channel.verAsientoAsync(request)
        End Function
        
        Public Function verAsientoAsync(ByVal transaccion As Long, ByVal idImg As Long, ByVal tipo As String, ByVal nroTotalPag As String, ByVal nroPagRef As String, ByVal pagina As String) As System.Threading.Tasks.Task(Of SUNARP_Consulta.verAsientoResponse)
            Dim inValue As SUNARP_Consulta.verAsientoRequest = New SUNARP_Consulta.verAsientoRequest()
            inValue.transaccion = transaccion
            inValue.idImg = idImg
            inValue.tipo = tipo
            inValue.nroTotalPag = nroTotalPag
            inValue.nroPagRef = nroPagRef
            inValue.pagina = pagina
            Return CType(Me,SUNARP_Consulta.PIDEWSService).verAsientoAsync(inValue)
        End Function
        
        Public Function verDetalleRPV(ByVal zona As String, ByVal oficina As String, ByVal placa As String) As SUNARP_Consulta.respuestaVehiculoBean Implements SUNARP_Consulta.PIDEWSService.verDetalleRPV
            Return MyBase.Channel.verDetalleRPV(zona, oficina, placa)
        End Function
        
        Public Function verDetalleRPVAsync(ByVal zona As String, ByVal oficina As String, ByVal placa As String) As System.Threading.Tasks.Task(Of SUNARP_Consulta.respuestaVehiculoBean) Implements SUNARP_Consulta.PIDEWSService.verDetalleRPVAsync
            Return MyBase.Channel.verDetalleRPVAsync(zona, oficina, placa)
        End Function
    End Class
End Namespace
