'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MININTER_Consulta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.mi.com/", ConfigurationName:="MININTER_Consulta.WS_persona_rq_ant")>  _
    Public Interface WS_persona_rq_ant
        
        'CODEGEN: Generating message contract since element name vUsuario from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function consultaDniGeneral(ByVal request As MININTER_Consulta.consultaDniGeneralRequest) As MININTER_Consulta.consultaDniGeneralResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function consultaDniGeneralAsync(ByVal request As MININTER_Consulta.consultaDniGeneralRequest) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaDniGeneralResponse)
        
        'CODEGEN: Generating message contract since element name vUsuario from namespace  is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function consultaNombreGeneral(ByVal request As MININTER_Consulta.consultaNombreGeneralRequest) As MININTER_Consulta.consultaNombreGeneralResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function consultaNombreGeneralAsync(ByVal request As MININTER_Consulta.consultaNombreGeneralRequest) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaNombreGeneralResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class consultaDniGeneralRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="consultaDniGeneral", [Namespace]:="http://ws.mi.com/", Order:=0)>  _
        Public Body As MININTER_Consulta.consultaDniGeneralRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MININTER_Consulta.consultaDniGeneralRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class consultaDniGeneralRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public vUsuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public vClave As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public vDNI As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public vEntidadconsulta As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public vDNIconsulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vUsuario As String, ByVal vClave As String, ByVal vDNI As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String)
            MyBase.New
            Me.vUsuario = vUsuario
            Me.vClave = vClave
            Me.vDNI = vDNI
            Me.vEntidadconsulta = vEntidadconsulta
            Me.vDNIconsulta = vDNIconsulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class consultaDniGeneralResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="consultaDniGeneralResponse", [Namespace]:="http://ws.mi.com/", Order:=0)>  _
        Public Body As MININTER_Consulta.consultaDniGeneralResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MININTER_Consulta.consultaDniGeneralResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class consultaDniGeneralResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class consultaNombreGeneralRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="consultaNombreGeneral", [Namespace]:="http://ws.mi.com/", Order:=0)>  _
        Public Body As MININTER_Consulta.consultaNombreGeneralRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MININTER_Consulta.consultaNombreGeneralRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class consultaNombreGeneralRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public vUsuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public vClave As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public vNom As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public vApe_p As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public vApe_m As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public vEntidadconsulta As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public vDNIconsulta As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vUsuario As String, ByVal vClave As String, ByVal vNom As String, ByVal vApe_p As String, ByVal vApe_m As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String)
            MyBase.New
            Me.vUsuario = vUsuario
            Me.vClave = vClave
            Me.vNom = vNom
            Me.vApe_p = vApe_p
            Me.vApe_m = vApe_m
            Me.vEntidadconsulta = vEntidadconsulta
            Me.vDNIconsulta = vDNIconsulta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class consultaNombreGeneralResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="consultaNombreGeneralResponse", [Namespace]:="http://ws.mi.com/", Order:=0)>  _
        Public Body As MININTER_Consulta.consultaNombreGeneralResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MININTER_Consulta.consultaNombreGeneralResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class consultaNombreGeneralResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_persona_rq_antChannel
        Inherits MININTER_Consulta.WS_persona_rq_ant, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_persona_rq_antClient
        Inherits System.ServiceModel.ClientBase(Of MININTER_Consulta.WS_persona_rq_ant)
        Implements MININTER_Consulta.WS_persona_rq_ant
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MININTER_Consulta_WS_persona_rq_ant_consultaDniGeneral(ByVal request As MININTER_Consulta.consultaDniGeneralRequest) As MININTER_Consulta.consultaDniGeneralResponse Implements MININTER_Consulta.WS_persona_rq_ant.consultaDniGeneral
            Return MyBase.Channel.consultaDniGeneral(request)
        End Function
        
        Public Function consultaDniGeneral(ByVal vUsuario As String, ByVal vClave As String, ByVal vDNI As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String) As String
            Dim inValue As MININTER_Consulta.consultaDniGeneralRequest = New MININTER_Consulta.consultaDniGeneralRequest()
            inValue.Body = New MININTER_Consulta.consultaDniGeneralRequestBody()
            inValue.Body.vUsuario = vUsuario
            inValue.Body.vClave = vClave
            inValue.Body.vDNI = vDNI
            inValue.Body.vEntidadconsulta = vEntidadconsulta
            inValue.Body.vDNIconsulta = vDNIconsulta
            Dim retVal As MININTER_Consulta.consultaDniGeneralResponse = CType(Me,MININTER_Consulta.WS_persona_rq_ant).consultaDniGeneral(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MININTER_Consulta_WS_persona_rq_ant_consultaDniGeneralAsync(ByVal request As MININTER_Consulta.consultaDniGeneralRequest) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaDniGeneralResponse) Implements MININTER_Consulta.WS_persona_rq_ant.consultaDniGeneralAsync
            Return MyBase.Channel.consultaDniGeneralAsync(request)
        End Function
        
        Public Function consultaDniGeneralAsync(ByVal vUsuario As String, ByVal vClave As String, ByVal vDNI As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaDniGeneralResponse)
            Dim inValue As MININTER_Consulta.consultaDniGeneralRequest = New MININTER_Consulta.consultaDniGeneralRequest()
            inValue.Body = New MININTER_Consulta.consultaDniGeneralRequestBody()
            inValue.Body.vUsuario = vUsuario
            inValue.Body.vClave = vClave
            inValue.Body.vDNI = vDNI
            inValue.Body.vEntidadconsulta = vEntidadconsulta
            inValue.Body.vDNIconsulta = vDNIconsulta
            Return CType(Me,MININTER_Consulta.WS_persona_rq_ant).consultaDniGeneralAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MININTER_Consulta_WS_persona_rq_ant_consultaNombreGeneral(ByVal request As MININTER_Consulta.consultaNombreGeneralRequest) As MININTER_Consulta.consultaNombreGeneralResponse Implements MININTER_Consulta.WS_persona_rq_ant.consultaNombreGeneral
            Return MyBase.Channel.consultaNombreGeneral(request)
        End Function
        
        Public Function consultaNombreGeneral(ByVal vUsuario As String, ByVal vClave As String, ByVal vNom As String, ByVal vApe_p As String, ByVal vApe_m As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String) As String
            Dim inValue As MININTER_Consulta.consultaNombreGeneralRequest = New MININTER_Consulta.consultaNombreGeneralRequest()
            inValue.Body = New MININTER_Consulta.consultaNombreGeneralRequestBody()
            inValue.Body.vUsuario = vUsuario
            inValue.Body.vClave = vClave
            inValue.Body.vNom = vNom
            inValue.Body.vApe_p = vApe_p
            inValue.Body.vApe_m = vApe_m
            inValue.Body.vEntidadconsulta = vEntidadconsulta
            inValue.Body.vDNIconsulta = vDNIconsulta
            Dim retVal As MININTER_Consulta.consultaNombreGeneralResponse = CType(Me,MININTER_Consulta.WS_persona_rq_ant).consultaNombreGeneral(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MININTER_Consulta_WS_persona_rq_ant_consultaNombreGeneralAsync(ByVal request As MININTER_Consulta.consultaNombreGeneralRequest) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaNombreGeneralResponse) Implements MININTER_Consulta.WS_persona_rq_ant.consultaNombreGeneralAsync
            Return MyBase.Channel.consultaNombreGeneralAsync(request)
        End Function
        
        Public Function consultaNombreGeneralAsync(ByVal vUsuario As String, ByVal vClave As String, ByVal vNom As String, ByVal vApe_p As String, ByVal vApe_m As String, ByVal vEntidadconsulta As String, ByVal vDNIconsulta As String) As System.Threading.Tasks.Task(Of MININTER_Consulta.consultaNombreGeneralResponse)
            Dim inValue As MININTER_Consulta.consultaNombreGeneralRequest = New MININTER_Consulta.consultaNombreGeneralRequest()
            inValue.Body = New MININTER_Consulta.consultaNombreGeneralRequestBody()
            inValue.Body.vUsuario = vUsuario
            inValue.Body.vClave = vClave
            inValue.Body.vNom = vNom
            inValue.Body.vApe_p = vApe_p
            inValue.Body.vApe_m = vApe_m
            inValue.Body.vEntidadconsulta = vEntidadconsulta
            inValue.Body.vDNIconsulta = vDNIconsulta
            Return CType(Me,MININTER_Consulta.WS_persona_rq_ant).consultaNombreGeneralAsync(inValue)
        End Function
    End Class
End Namespace
